FROM node:18

WORKDIR /app

# Kopírujeme konfigurační soubory pro npm
COPY package*.json ./

# Instalujeme závislosti
RUN npm install

# Kopírujeme zbytek souborů
COPY . .

# Expose port for development server
EXPOSE 3000

# Spuštění vývojového serveru přímo přes npx
CMD ["npx", "vite", "--host", "0.0.0.0"]