FROM node:18

WORKDIR /app

# Kopírujeme konfigurační soubory pro npm
COPY package*.json ./

# Instalujeme závislosti
RUN npm install

# Kopírujeme zbytek souborů
COPY . .

# Expose port for development server
EXPOSE 3000

# Spuštění vývojového serveru pomocí npm skriptu s parametrem host
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]